### PR TITLE
multicall2 allow failures

### PR DESCRIPTION
**Pull request by willpote**
Forking @JFrankfurt [PR](https://github.com/makerdao/multicall/pull/18) as he is away. Updated the README with contract addresses and an explanation of Multicall2.

### CODE REVIEW

**Comment by moodysalem** [comment]
@gbalabasquer can you please TAL? We are using this widely in the Uniswap interface, and it is also something that I've seen requested on twitter, and I come back to this repo occasionally to look at the code

**Comment by ethanbennett** [comment]
I think what we need here is to find a way to open this up so the Maker team isn't a bottleneck anymore, or to transition the ownership to one of the DAO domain teams--many of the people who worked on it have since moved on. I'll bring this up to the current team and do what I can to get this unblocked (I'm also no longer at Maker, so I can't directly approve these changes)

**Comment by wkampmann** [comment]
We're looking for a new owner for this. I'm reaching out to @michaelelliot to see if he's interested and will discuss it with the front-end DAO team too.

**Comment by wkampmann** [comment]
Invited @michaelelliot as maintainer for this repo.

**Review by ethanbennett — APPROVED** [review]
I was added to the repo as well, and this one looks good to me. It might be a minute before I have the time to go through all these other PRs (hopefully Michael will be more helpful for those), but feel free to let me know if there are any others that are especially high priority and should get some immediate attention @moodysalem

**Pull request merged**
