### PR TITLE
Allow calls to fail and return the block hash.

### PR DESCRIPTION
**Pull request by WyseNynja**
Sometimes I'm aggregating calls and I expect some failures. This lets me aggregate them.

Returning the block hash helps me in the event of a re-org.

### CODE REVIEW

**Comment by WyseNynja** [comment]
Mainnet: 0xeCCE0ba5d8E2C8Fa9c045722ff0B9b11d5111B30
Ropsten: 0x573414DdCF9FF6D60d4001DAB1A7D682Cec4e4BE

**Comment by rotcivegaf** [comment]
I like this upgrade, but I dont like the lint and i think you dont respect the previos architecture
I make this [PR](https://github.com/SatoshiAndKin/multicall/pull/1)

**Comment by WyseNynja** [comment]
What do you mean by "respect the previous architecture?" I didn't want to reuse the function name since it works differently.

**Comment by moodysalem** [comment]
can you branch the file into `Multicall2.sol` instead of changing `Multicall`? I like/need this change

**Comment by ethanbennett** [comment]
I believe this was covered by #21

**Pull request closed without merging**
